### ISSUE TITLE
Memory problem with R

### ISSUE THREAD

**Issue by eva0marques** [Spatiotemporal-Exposures-and-Toxicology/Spatiotemporal-Exposures-and-Toxicology#1]
To run ML model (XGBoost for eg.), I initially wanted to create a data.frame with each line corresponding to an observation on day j, sensor s. The problem: we have 1058 sensors * 365.2 days * 5 years = 1931908 observations with 3844 covariates. I unsurprisingly get an error message "Error: vector memory exhausted (limit reached?)". I don't know if any of you have a different solution, but my idea is to use parallel computing on each cross validation batches, hoping they won't be too massive...

**Comment by kyle-messier** [comment]
@eva0marques  I am going to close this and open a more comprehensive task/discussion on memory and big data management
